
name: IssueOps Branch Creator
# TODO: Implement the ChatOps logic here
on:
  issue_comment:
    types: [created]

jobs:
  branch-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
